language: cpp
os: linux
dist: focal
compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'ppa:beineri/opt-qt-5.15.2-focal'
    update: true
    packages:
    - qt515base
    - qt515tools
    - qt515svg
    - qt515charts-no-lgpl
    - qt5153d
    - libgl-dev
    - libgl1-mesa-dev
    - mesa-common-dev
    - libcfitsio-dev 
    - libtiff-dev 
    - libxml2-dev 
    - libhdf4-0
    - libhdf4-dev
    - libhdf5-103
    - libhdf5-dev
    - libnexus1
    - libnexus-dev
    - libfftw3-dev 
    - libarmadillo9 
    - libarmadillo-dev
script:
  - /opt/qt515/bin/qt515-env.sh
  - export WORKSPACE=`pwd`/..
  - export QTBINPATH=/opt/qt515/bin 
  - build/build_all.sh
  - ls ../lib
